
name: local
stages:
  - ingestion
  - standardization
  - feature_building
  - signal_generation
  - execution
  - evaluation

enabled:
  ingestion: True
  standardization: True
  feature_building: True
  signal_generation: True
  execution: True
  evaluation: True

configs:
  dataset: configs/datasets/sector_daily_5min_rv.yaml
  strategy: configs/strategies/sector_state_signal_long_short.yaml
  connections: configs/connections/test_paper_account.yaml

storage:
  backend: local
  base_dir: "."
