
name: local
stages:
  - ingestion
  - standardization
  - feature_building
  - signal_generation
  - execution
  - evaluation

enabled:
  ingestion: False
  standardization: False
  feature_building: False
  signal_generation: True
  execution: True
  evaluation: True

configs:
  dataset: configs/datasets/sector_daily_5min_rv.yaml
  strategy: configs/strategies/sector_state_signal_long_only.yaml
  connections: configs/connections/paper_1.yaml

storage:
  backend: local
  base_dir: "."
