
name: live_trading
stages:
  - ingestion
  - standardization
  - feature_building
  - signal_generation
  - execution

enabled:
  ingestion: True
  standardization: True
  feature_building: True
  signal_generation: True
  execution: True

configs:
  dataset: datasets/sector_daily_5min_rv.yaml
  strategy: strategies/sector_state_signal_long_only.yaml
  connections: paper_1.yaml

logging:
  level: INFO
  log_to_stdout: true

storage:
  backend: s3
  bucket: quant-trading-project
  prefix: quant-trading
  region: us-east-2